[tool.poetry]
name = "aula-08-bootcamp"
version = "0.1.0"
description = ""
authors = ["Roberto Melo Jr <robertomelojr@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
